# Generated by Django 2.2.4 on 2019-08-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190830_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='isactive',
            field=models.BooleanField(default=False),
        ),
    ]
